# Generated by Django 4.1.5 on 2023-06-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('buy', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bidproducts'),
        ),
        migrations.CreateModel(
            name='win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=100)),
                ('bid_win_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bidproducts')),
            ],
        ),
    ]
