# Generated by Django 4.1.5 on 2023-05-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('start_price', models.IntegerField()),
                ('image', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('category', models.CharField(max_length=64)),
                ('bid_active', models.BooleanField(default=True)),
            ],
        ),
    ]
