# Generated by Django 4.1.5 on 2023-07-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidproducts',
            old_name='user',
            new_name='username',
        ),
    ]
